export type UserProfileInformation = {
  id: string;
  userId: number;
  username: string;
  email?: string;
  emailVerified?: boolean;
  role?: string;
  level: number;
  firstName?: string;
  lastName?: string;
  profilePhoto?: string;
  phone?: string;
  referralCode?: string;
  referralCount?: number;
  points?: number;
  dailyFreeBoosters: number;
  dailyBoostersExp?: Date;
  createdAt?: Date;
  updatedAt?: Date;
};
